/* 
FIX ng4SDTLead -->a9p_ProjectManager attribute mapping from Ng4_MasterPrgRevision  to A9_ProgramItemRevision
ng4SDTLead -->a9p_ProjectManager (Its wrongly transformed to UID of ng4SDTLead User,instead of mapping string value. 
We need to update correct values in target. */

Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='atiank' where puid='StTJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='ajohnsk0' where puid='yBeJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='aformep' where puid='RreJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='adue' where puid='TeZJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='azhangtr' where puid='EPZJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='RvRd0IAlIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='yRUdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CqUdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='matrin.sandmann@yfai.com' where puid='1aadEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Tian Qing' where puid='m$RVMRf4IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='huachun xue' where puid='kjZVMRf4IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='???' where puid='pKTVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Amy Fu' where puid='XLVVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='RLed0IAlIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='t2XdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='92VdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='hdbdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='BmTdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='RbZdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='SXQdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='ewedDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Axel Koever' where puid='CBbdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='7JRdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='LuVdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='rSVdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='christopher.warp@yfai.com' where puid='h5ZdiMMZIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='yFcd9CBwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Diedre Kutscher' where puid='ReVd0TwcIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='hrcdYJRtIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CCchhCnWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='idXd__fNIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='RXXd0NHuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='SETd0NHuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Stephen Asaro' where puid='nSbdb$NnIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Mark.kadzban@yfai.com' where puid='CfdhCbh6IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='SORdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='iGTdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='y6YdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Peter Gruedl' where puid='iwRdHH$6IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='SVRdHH$6IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='ChQdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='tanja.pilger@yfai.com' where puid='ShWdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Tess Stanek' where puid='CRXhKTRrIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Linda Lee' where puid='NpfhtCGBIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Kevin Page' where puid='CaWlR_ilIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Kevin Page' where puid='SyWlR_ilIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Matt Klinkman' where puid='C1RlCVS6IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='alizg' where puid='UjZJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='amarzoma' where puid='RNeJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='ixRdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='GQYdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='fabian.schmidt@yfai.com' where puid='RjYdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Jianmin Yang' where puid='jDVV8E4zIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Lydia Wang' where puid='GxYVMRf4IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Qin Zheng' where puid='kSZVMRf4IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='TBD' where puid='JjfVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Guoding Tang' where puid='mhYVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='christopher.warp@yfai.com' where puid='9dTdSCcfIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='Brbd0IAlIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Annie Chen (achenas)' where puid='0NeVNRgYIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER=',' where puid='0PWVNRgYIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='eSRdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='7ySdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='dWadDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='d2ZdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='d3RdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='tXQdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='RGWdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='xGSdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='xmVdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CTadDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CzddDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='S3TdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Fred Greal' where puid='zNfdiWZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='_wcdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='ORbdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Steven Swiftney' where puid='GVWdzIs9IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='rpSdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='ryUdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='j8RdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='tanja.pilger@yfai.com' where puid='SmWdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='David Cordle' where puid='xKcdEtnpIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='_gQd7C7hIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Nathan Bellamy' where puid='tIbdY9zmIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='etad7C7hIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='KEVdfLJPIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='TuRhDOdcIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='z6ZhDOdcIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='ySVduLHwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Jerry Kratz' where puid='i8UdeKQVIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Steve Swiftney' where puid='GKcdXTYuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='mUUdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='iSfdeYQrIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='astrid.skoupi@yfai.com' where puid='CDbdeYQrIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='S3Yd7Vi8IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='James Merline' where puid='y8Zh2uL5IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='Rffdn0RFIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Stephen Asaro' where puid='XSadb$NnIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='2_ShCgi9IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Jason Moser' where puid='WJcd$wY_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='ELYhHCOlIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Swamy Gopalakrishnan' where puid='yYQd9ByOIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='j2XdYDcXIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='yeadINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Dirk Petersen' where puid='N7Zd4L0gIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Fred Greal' where puid='6JThCowOIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Roland Meyer' where puid='6QYhj81LIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='hWZdVorJIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Marcin.Ligeza@adient.com' where puid='TwahssMgIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Chenghui Fan' where puid='C5aljxbuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Budd Bentley' where puid='CtblRrjwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Marcus Hollander' where puid='57ThKDibIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Zelan Banks' where puid='CZfh_sNEIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Jerry Kratz' where puid='ChclR_ilIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Mark Yenkel' where puid='C9TlTao$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Rich Simons' where puid='XwVlTao$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='akalemb' where puid='BIdJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='afellij' where puid='EbUJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='aklaust' where puid='lsWJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='atiank' where puid='kPcJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='tanja.pilger@yfai.com' where puid='leVdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Lars Andre Neubauer' where puid='FHXdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='VHddEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Peter Oppermann' where puid='FnadEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='lrWdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Andreas Ulbricht Kraft' where puid='1LZdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Ingo Trentmann' where puid='BjSdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Fu Ming(FJC)' where puid='WueVMRf4IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='hqSd0IAlIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Xu Bo' where puid='0qXVs29OIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Kevin Heintz' where puid='1CbVs29OIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='_RVdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Christopher Warp' where puid='25XZeqd7IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='dXSdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='tzfdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='93SdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='tanja.pilger@yfai.com' where puid='SpXdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='iyRdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='eQfdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='eRZdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='exYdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='h7WdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='x7cdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='byWdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='i3ZdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='D4VdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='jYedDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='SKdd9CBwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='KRSd7C7hIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='John Hoekwater' where puid='2CZhS4wgIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='John Hoekwater' where puid='2bUhS4wgIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='zdZhDOdcIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='uRYd7C7hIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='zWbhDOdcIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='i5bduLHwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='abakalr' where puid='DvYdbgcxIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='SxUdt4phIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Fred Greal' where puid='6ZbhnPsTIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Darin Adgate' where puid='KkddKzA7IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Kevin Chavez' where puid='GIddmy4CIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Darin Adgate' where puid='muYhWLsDIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Jeff Klimecki' where puid='yUbd8Jf0IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Michael Sherry' where puid='FKYdGH2MIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='W0RdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Joel Smith' where puid='x6UdXhMkIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='SyRdeYQrIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Jerry Kratz' where puid='RaadFSKGIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='astrid.skoupi@yfai.com' where puid='CnZdeYQrIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='hXdd0NHuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='h7Qd0NHuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Victor Belloch Blanco' where puid='rSWhgHXgIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='SLchHCOlIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='S9VdYDcXIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='COSdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Yiqing Zhao' where puid='q9Yh4p6iIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Michael Mundy' where puid='2rXdege_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='icUdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='y8ddpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='ihcdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='RHddVorJIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Philippe.Boehler@adient.com' where puid='HgchM6FHIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Nick Giffel' where puid='ioflR9jpIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Michael Sherry' where puid='S9dlUWkfIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='akleinc4' where puid='9YShtCGBIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Steve Gumpert' where puid='SGXlR_ilIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Fred Greal' where puid='StWl0A1BIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='John Hoekwater' where puid='Sidl0A1BIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='awangc7' where puid='iJVJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='achenas' where puid='iXYJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='atiank' where puid='ksbJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='atrenti' where puid='ECQJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='awycksph' where puid='zjZJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='D3Qha0pIIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='iqfhZ6HUIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='iIUdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='StbdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Dirk Petersen' where puid='VrQdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Jianmin Yang' where puid='1XZVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Jianhua Zhu' where puid='mQeVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Lydia Wang' where puid='WrbVs29OIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='LJZdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='LpYdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='tWYdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='R7YdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Dirk Soltau' where puid='ypfdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='hbXdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='igSdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='ygYdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='ChadjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='TYYdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Ingo Trentmann' where puid='zcUdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='tanja.pilger@yfai.com' where puid='iGZdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='i2Rd9CBwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='u8Sd7C7hIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='TNRhDOdcIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='DmVhDOdcIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='SGYduLHwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='y2QduLHwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Kevin Page' where puid='y8chWLsDIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Mike S Mundy' where puid='XiXdeKQVIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='thomas.erprath@yafai.com' where puid='m0XdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Joel Smith' where puid='xpfdXhMkIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Gitte Herbert' where puid='aqTdrDGiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Martin.Sandmann@yfai.com' where puid='6WbdrDGiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='y1cdvflaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='D4ThVQMpIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CnehHCOlIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='iEVdJ_RzIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Jason Moser' where puid='iYbd$wY_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='akutscd' where puid='qZUdVp2RIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Eric Snyder' where puid='YZQdePUVIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CRddYDcXIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='idYdYDcXIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Wendy Brummel' where puid='icfhBfGfIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Wendy Brummel' where puid='mRThBfGfIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Hideaki Okuyama' where puid='CNShI6zpIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Michael Mundy' where puid='rwWdvXwhIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Yiqing Zhao' where puid='icahxJvCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Mike S Mundy' where puid='K8QhR_bsIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='iSXhCfomIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Fred Greal' where puid='5yZdYR3NIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Zhang Yafei' where puid='iQahiFtwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='SwcdHH$6IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='tanja.pilger@yfai.com' where puid='yhedpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Yuanye.cheng@adient.com' where puid='yTZhssMgIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Teresa Stanek' where puid='C1alSnMxIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Steve Hildebrandt' where puid='GLdlECCwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='EJQh9swrIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='atiank' where puid='U8YJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Christopher Warp' where puid='JuddB_AHIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='akleinc4' where puid='j4aJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='atiank' where puid='DtcJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Bee.Kak.Teo@jci.comA ' where puid='1ccNWcbIIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='atiank' where puid='CxVJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='atiank' where puid='izfJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Fred Greal' where puid='IHZdgn_9IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='christopher.warp@yfai.com' where puid='_rSdSGdBIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='azhan57' where puid='SNcJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Ken Vanderlaan' where puid='FeadB2W1IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='xnVdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='SoRdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='SKXdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='christopher.warp@yfai.com' where puid='hGZdyW7AIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='WangCHao' where puid='UiXVMRf4IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Susan Zhang' where puid='3icVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Yinjie Zhao(Global,China),Francisco Moreno(EU),Kimoto(Japan)' where puid='IXfVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Daniel Han' where puid='pJaVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Brett W. Kalem' where puid='WqSVs29OIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER=',' where puid='27WVNRgYIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='TdSdT$1PIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='_xUdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='7oadD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='rJUdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='tVbdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='N2ZdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='NXUdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='9XQdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='BHUdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='BjSdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='C4edjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='bOUdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='jOfhDOdcIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Rajkumar G' where puid='CpRd1GidIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CidduLHwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='SqTduLHwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='S2ddt4phIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Mike S Mundy' where puid='XETdeKQVIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Nina France' where puid='1HYdYDq4IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='yFfdeYQrIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Martin.Sandmann@yfai.com' where puid='aVXdrDGiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Lydia Wang' where puid='aGVdrDGiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Swamy Gopalakrishnan' where puid='HzfdNHEKIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='B3Ud0NHuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='CIfd0NHuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='iVUdvflaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='S_fhHCOlIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Phillip George' where puid='icYhgGY4IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='0mahHCOlIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='yNQdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='ypfdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Mike S Mundy' where puid='GxadehOhIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Jerry Kratz' where puid='a9RhR_bsIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='yyehCfomIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Elisabet.Anderson@yfai.com' where puid='xQRZfX8jIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='CsddHH$6IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='hvQdHH$6IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='S8RdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Steven Shang' where puid='aRdhLJtqIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Swamy Gopalakrishnan' where puid='XBalR0UvIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Budd Bentley' where puid='ieWlRrjwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Kevin Page' where puid='6bXlmhyjIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Steven Shang' where puid='jcVhLFK1IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='7AVllQRmIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Tess Stanek' where puid='GhahKrfMIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Nick Giffel' where puid='qGflUYFzIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='amarzoma' where puid='THVJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='ayangno' where puid='EcSJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='amarzoma' where puid='0TYJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='afuam' where puid='DaVJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='abakalr' where puid='iMQJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Swamy Gopalakrishnan' where puid='88dhJu2nIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='christopher.warp@yfai.com' where puid='uTfdSGdBIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Roland Meyer' where puid='JJedR5GqIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='atiank' where puid='T1QJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='michael.gericke@yfai.com' where puid='ioXdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CtVdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='1nbdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='RDVdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='hDbdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Wenzhong Wang' where puid='30dVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='???' where puid='pmfVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='christopher.warp@yfai.com' where puid='daVdSCcfIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Hrvoje Martin Grajzar' where puid='3SYdzL5LIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER=',' where puid='VYQVNRgYIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='OSTdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='OySdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='D1ddT$1PIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='r0VdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='9WWdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='RmVdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='hGUdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='SOYdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='SubdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='OURdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='O0QdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='OxadDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='uRXdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='SYddjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Darin Adgate' where puid='WsedzIs9IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='j5bhDOdcIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='gitte.herbert@yfai.com' where puid='LddhUSJpIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='WQedEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='SOTdeYQrIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='ySXd7Vi8IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Sanjeev Umley' where puid='6ZbdrDGiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Helle Hu' where puid='KiXdrDGiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='kyRhVQMpIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Stephen Asaro' where puid='WPXdb$NnIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CHQhHCOlIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Yuki Kanemaru' where puid='y0RhSzWXIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='David Cordle' where puid='JPbdWXXtIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='D$VdYDcXIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='STTdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='SvVdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Mike S Mundy' where puid='bcehBu48IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='iQfdHH$6IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='i8XdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Marcin.Ligeza@adient.com' where puid='zKehssMgIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='David Wilganoski' where puid='CZUhsyeCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Swamy Gopalakrishnan' where puid='60YhLOM8IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Eric Snyder' where puid='L6dlUSg3IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Timothy Mcintee' where puid='ScYlwUnaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Ken Vanderlaan' where puid='Kxalj5yOIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Darin Adgate' where puid='rcblj5yOIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='akleinc4' where puid='tkXhtCGBIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Ken Vanderlaan' where puid='CZelA7TPIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='ashangzh' where puid='xFQJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='ali814' where puid='DAUJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CEYdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Roland Meyer' where puid='SEedEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='yIadEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='yoddEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CNSdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='ytWdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='astrid.skoupi@yfai.com' where puid='V_SdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='l_YdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Qin Zheng' where puid='T2TV8E4zIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Mohamad Zaki' where puid='IqeVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Amy Fu' where puid='WBUVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='christopher.warp@yfai.com' where puid='BzbdS2ybIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Steven Shang' where puid='FZeVs29OIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='bJXdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='COSdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='iOedDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Eric Snyder' where puid='2zbZvmkmIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='uQddDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='_QddDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='CYfdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='7xSdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='7STdD5DCIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='Syfd9CBwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Jason Moser' where puid='ycZhS4wgIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='John Hoekwater' where puid='GbYhS4wgIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='eiWd7C7hIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='yFWhhCnWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='S9aduLHwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CCSduLHwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='iKeduLHwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='iuaduLHwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Martin Sandmann' where puid='57bd3uXdIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Kenneth Vanderlaan' where puid='3UddeKQVIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Mike S Mundy' where puid='3iadeKQVIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='akutscd' where puid='5fQd0Dg2IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Tim Hall' where puid='69ZdrDGiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Gitte Herbert' where puid='qKQdrDGiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='R3ad0NHuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='CoRd0NHuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Diedre Kutscher' where puid='LQbhI4dTIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='CXWdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='CzUdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Mike S Mundy' where puid='aFQhR_bsIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='CXchCfomIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='SQZdHH$6IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='tanja.pilger@yfai.com' where puid='iBZdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='yBfdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='CmQdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Budd Bentley' where puid='m3alBgtdIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='ashangzh' where puid='ioXJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='atiank' where puid='jiYJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Fred Greal' where puid='EUcdgn_9IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='achenas' where puid='xDWJX$iiIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='hjedEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='xHRdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='marin.sandmann@yfai.com' where puid='CkbdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='SNYdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='iNedEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='lLTdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='christopher.warp@yfai.com' where puid='hqTdyW7AIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='???' where puid='UKVVcsqMIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Wenzhong Wang' where puid='ZDbVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Linda Lee' where puid='lsRVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Qin Zheng' where puid='VJYVMONuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Catherine Chen' where puid='24WZPFdSIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Dominika Mojzisova' where puid='8yXdzEawIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='NWbdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='N3TdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='hmTdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CuVdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='ySUdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='yyXdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='iXWdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='uwddDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='uxWdDtzaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='xbZdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.comm' where puid='yAVdjA49IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='yXcdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='y3fdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='DYSdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='T4bdDXZQIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='yiYd9CBwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Robb Vanderkamp' where puid='CNfh4TvLIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='OBed7C7hIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='DCXhDOdcIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='eJcd7C7hIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='u1Wd7C7hIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='jydhDOdcIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='ydXduLHwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='CXbduLHwIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Michael Beck' where puid='ZKcd3WNmIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Steve Swiftney' where puid='mqTdXTYuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Steve Swiftney' where puid='xGUdXTYuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='heiko.lemke@yfai.com' where puid='GwbdEBe$IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Swamy Gopalakrishnan' where puid='yoXhyU5rIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='astrid.skoupi@yfai.com' where puid='iycdeYQrIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='SbRd7Vi8IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Steven Swiftney' where puid='KsTd$qK2IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='BXRd0NHuIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='yVRdvflaIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Stephan Asaro' where puid='HScdb$NnIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='zWadYDcXIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='z2ddYDcXIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='DbQdYDcXIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='E4cdYDcXIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='0AcdYDcXIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='CpadINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='iBXdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='ipddINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='CufdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='yCcdINx_IRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Kenneth Vanderlaan' where puid='K2QhR_bsIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='C7ahCfomIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='x7YdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='ycadpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='tanja.pilger@yfai.com' where puid='CGRdpdxWIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='mark.kadzban@yfai.com' where puid='K0fd_6ksIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Matt Klinkman' where puid='8VWlkeMpIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='Zelan Banks' where puid='KVVlxGXoIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='TBD' where puid='JcThO93zIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='martin.sandmann@yfai.com' where puid='bBellQRmIRyNID';
Update pA9_ProgramItemRevision set PA9P_PROJECTMANAGER='astrid.skoupi@yfai.com' where puid='ayTljr6zIRyNID';
commit;